### ISSUE TITLE
[SUGGESTION] Manage Dropout Scholars

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#10]
**Is your feature request related to a problem? Please describe.**
Sometimes in the middile of a payment period a scholar drops off. Add a means to account for that

**Describe the solution you'd like**
Not sure how to implement this yet...

I welcome ideas for how to solve this.

**Comment by osirisss11** [comment]
Also not sure if this has been addressed yet but is there an option when paying from scholars account to send a % to managers address but also send % to trainers within the same transaction. 

Eg split the % to multiple addresses?

**Comment by FerranMarin** [comment]
There are the fields for Trainer Ronin and Trainer amount. So yes, you can pay from an account to the scholar, the manager and optionally to a trainer. That is already implemented.

**Comment by FerranMarin** [comment]
Update: I will probably be adding a percent option to pay based on percents and not full ammounts. See: https://github.com/FerranMarin/axie-scholar-utilities/issues/19

**Comment by FerranMarin** [comment]
Not gonna address this, no clarifications as how this should be addressed. Closing this issue for now.
