### ISSUE TITLE
[SUGGESTION] Support Trezor Accounts

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#17]
**Is your feature request related to a problem? Please describe.**
If you secure your account with trezor device, they cannot get the private keys, so this tool cannot work.

**Describe the solution you'd like**
Tool works, each signature the user is prompted to sign using trezor.

**Comment by nakwon3** [comment]
How is this effort coming along? I am currently managing 50+ scholars on a Trezor hardware wallet and can't wait until there's an automated solution for SLP payout. Thanks for having this on the priority list.

**Comment by FerranMarin** [comment]
I am finishing it up right now. Adding a few more tests but it already works. Join the discord and mention you wanna test the trezor and you can start setting it up already. Else, it will be out there in a few hours :)

**Comment by nakwon3** [comment]
That's amazing! Where can I find the Discord invite?

**Comment by FerranMarin** [comment]
https://discord.gg/bmKvmhenvu
It's also in the README

**Comment by FerranMarin** [comment]
This PR adds support for trezor!
https://github.com/FerranMarin/axie-scholar-utilities/pull/60
