### ISSUE TITLE
[SUGGESTION] Add Percent Payments Method

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#19]
**Is your feature request related to a problem? 
Some users want the payments to be based on % and not the full amounts.

**Describe the solution you'd like**
I'll create an alternative json schema to identify payments by percent from payments by full amount in the payments.json file.

**Comment by FerranMarin** [comment]
This is also very needed as it will prevent any issues coming from claiming while the scholar is paying and the data in a tracker is still to be updated. No SLP's will be left on the ronin accounts anymore!

**Comment by daryledesilva** [comment]
yes this was what i was expecting too when i read the documentation. earnings of scholar can change based on performance so it makes more sense to use percentage vs fixed values when you automate payments

**Comment by FerranMarin** [comment]
Implemented by: https://github.com/FerranMarin/axie-scholar-utilities/pull/28
