### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ppcftw1** [FerranMarin/axie-scholar-utilities#21]
**Describe the bug**
leaving "ronin:...." as is in the payments.json file, will make everything run fine until it tries to pay, there should be an error before informing it will occur so it doesnt claim and then try to pay the scholar/donation/other account. 

I didnt test if the other accounts would have sent first, and then have an error for the manager or what. 

**To Reproduce**
leave ronin address in payment file for manager as is, and run program with everything else present (axie.manager pay file, secrets, etc)

**Expected behavior**
I think in the worst case, tho i did not send payments, the scholars and donation may process but not the manager payment. im not sure if someone who wouldnt notice would then update the axie.manager pay file again and the next occurance would do same, pays sent but not for manager %. Not sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/91093116/134069389-88c85c48-b96c-48a7-94b9-f2a41d8c13ae.png)

**Desktop (please complete the following information):**
windows, powershell

**Comment by FerranMarin** [comment]
Fixed in this commit: https://github.com/FerranMarin/axie-scholar-utilities/commit/b678cb9f69fafb5d1be64b52c8b397dcbccf75e3
Thank you for the report!
