### ISSUE TITLE
[SUGGESTION] 0 SLP scholar, log error, but dun stop execution...

### ISSUE THREAD

**Issue by ppcftw1** [FerranMarin/axie-scholar-utilities#22]
**Is your feature request related to a problem? Please describe.**
trying to run the payments, if there is one scholar with 0 slp to pay, the program will stop and not conitnue, you do not have the choice to continue.

**Describe the solution you'd like**
if there is an error where an account will not send payments, have the choice to log the error and continue to next.

**Describe alternatives you've considered**
leave as is, 

**Additional context**

![image](https://user-images.githubusercontent.com/91093116/134069707-4e5dfb5d-63c1-49f5-b19e-caca56d50ac6.png)

**Comment by FerranMarin** [comment]
I'm thinking about this one... and it is not a bad suggestion, but I feel you want to have all valid transactions in the file so you can run them all at once and not need to be worried that some failed, specially due to stuff you can fix.

**Comment by FerranMarin** [comment]
I've decided not to implement this. I am happy to stop before it's starting and asking the user to correct payments.json.
