### ISSUE TITLE
[SUGGESTION] Add Transfer File Creation from CSV

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#41]
**Is your feature request related to a problem? Please describe.**
Transfer axies need a JSON file to be created, that can be a bit hard to create.

**Describe the solution you'd like**
Have a way to generate such JSON file via a CSV file.

**Additional context**
Other JSON files already have such helper functions.

**Comment by blanxii** [comment]
Quick win, I'll take it

**Comment by FerranMarin** [comment]
Added to main branch.
