### ISSUE TITLE
[SUGGESTION] Increase security

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#46]
**Is your feature request related to a problem? Please describe.**
Tool uses the secrets.json file where a bunch of private keys are stored. Currently security burden is on the user.

**Describe the solution you'd like**
Find a way to make storing that file in a personal computer safer. Maybe some sort of encryption?

**Describe alternatives you've considered**
Stay as we are, which is ok, but can be better.

**Additional context**
Many users, run this tool on their personal computers. Dangerous activities in werid places of internet or downloading suspiccious stuff could endanger their wallets if they did not take any measures. I want to help them stay safe.

**Comment by FerranMarin** [comment]
https://www.thepythoncode.com/article/encrypt-decrypt-files-symmetric-python
Might add some sort of capability to encrypt files with a password the users can chose that will be used to encrypt/decrypt files

**Comment by empeje** [comment]
Hi thank you for the great tools @FerranMarin 

I'm thinking how about we sign the txn manually outside the CLI. So the tools give me a code to sign and I use metamask or ronin wallet itself to sign, so no private key leaving wallet I have.

I wonder if that is possible?
