### ISSUE TITLE
[SUGGESTION] Transfer/Gift Axies

### ISSUE THREAD

**Issue by felixsim** [FerranMarin/axie-scholar-utilities#5]
Could you add a feature that allows us to send Axies from and to accounts?

**Comment by FerranMarin** [comment]
Thanks for the suggestion. I will need to check first the ToS, I am not clear if automating that would go against the terms of the game. After that, if it's ok, I will look into it :)

**Comment by FerranMarin** [comment]
I have checked ToS and apparently I do not see anything that would be going against them if I implement this. I will be looking to implement it soonish. Stay tunned :)

**Comment by felixsim** [comment]
AWeeeesome!!!!

**Comment by FerranMarin** [comment]
I need a cheap axie donated to me so I can test it locally. If someone donates one (I can give it back if you want once I'm done implementing this).
Without it, coding this will be VERY hard.

**Comment by FerranMarin** [comment]
I have a donated axie, I will be trying to implement this sometime soon.

**Comment by FerranMarin** [comment]
It's been added. Needs documentation and extra tests, but it's there and working :)
