### ISSUE TITLE
Auto-Payouts is free? Or incurs ETH gas fees?

### ISSUE THREAD

**Issue by kangzeroo** [FerranMarin/axie-scholar-utilities#52]
@FerranMarin great tool! I have a question about the automated payments.
Will using the automated payments incur ETH network fees? Or is it free because it uses the Ronin sidechain?

I took a look at the automated payments code in the below line, it looks like its swapping out the Ronin address for an Ethereum address:

https://github.com/FerranMarin/axie-scholar-utilities/blob/3526b76cecd639fe87d1061b5f0cae6384d73e14/axie-scholar-utilities/source/axie/payments.py#L41

At the same time, the web3 provider being loaded is the free Ronin provider.

https://github.com/FerranMarin/axie-scholar-utilities/blob/3526b76cecd639fe87d1061b5f0cae6384d73e14/axie-scholar-utilities/source/axie/payments.py#L38

Will using the automated payments incur ETH network fees? Or is it free because it uses the Ronin sidechain?

**Comment by FerranMarin** [comment]
Hello @kangzeroo  Sorry for the late reply.

It uses the ronin network. "ronin:" is just a visual thing, but on the chain level all addresses are 0x,thus why the replacements, to not confuse the user when they introduce their ronin addresses but still use the correct one.

Fees are non existent as of now on the ronin network, but RON has been introduced so... in the near future I am afraid fees will be a thing in the side chain too.

Hope this answers your question.
