### ISSUE TITLE
free gas rpc[SUGGESTION]

### ISSUE THREAD

**Issue by Kratoshate** [FerranMarin/axie-scholar-utilities#54]
hi, any improvement to the daily free gas limit ?, 100 transactions may be too few for some people.

**Comment by FerranMarin** [comment]
I would love to give everyone unlimited but... that is something on the chain level and this is only a tool that interacts with it. Sorry.

On a side note, with the intro of RON, you probably won't have the 100 limit, you will simply pay some ron as a gas fee.
