### ISSUE TITLE
[BUG] 403 Client Error: Forbidden for url: https://proxy.roninchain.com/free-gas-rpc

### ISSUE THREAD

**Issue by y66721986** [FerranMarin/axie-scholar-utilities#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Add files if related**
Just remmember NOT to send any private keys!

**Comment by FerranMarin** [comment]
That is a problem with the node being overloaded, nothing I can do from here.
