### ISSUE TITLE
403 Client Error: Forbidden for Url: https://api.roninchain.com/rpc

### ISSUE THREAD

**Issue by ddunham121** [FerranMarin/axie-scholar-utilities#58]
**Describe the bug**
When trying to run the payout command, it fails with this error message
403 Client Error: Forbidden for Url: https://api.roninchain.com/rpc

Claims on SLP seem to be working fine though, so it seemed odd that one worked and the other didn't.

**To Reproduce**
1. Run the payout command

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS - Latest
 - Browser: Firefox - Latest

**Additional context**
We run the commands using Poetry - if that's relevant 

**Add files if related**
Just remmember NOT to send any private keys!

**Comment by FerranMarin** [comment]
Hello!
Thank you for the report, but the RPC endpoint is currently blocked on the ronin network due to very high traffic. Nothing I can solve on my end.
Regrads,
Ferran
