### ISSUE TITLE
[SUGGESTION] Flexible Payments

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#61]
**Is your feature request related to a problem? Please describe.**
More and more ways to pay, ie, minimum and rest for scholar and many others.

**Describe the solution you'd like**
A truly flexible way to do payouts. So anyone can adapt it to their needs.

**Describe alternatives you've considered**
Stay as we are, but that loses us users that need some flexibility on the systems

**Additional context**
Many users requested if their own specific way of dealing with payments is possible and we have to come up with different ways to adapt their needs to the system. let's do the oposit!

**Comment by limitlessme25** [comment]
I would like to be able to take a daily quota then a percentage of the remainder. 

E.g. 75 SLP + 20% to manager daily.. 

This could help managers protect investment but getting a minimum amount before % splits.

**Comment by FerranMarin** [comment]
will take that into account, thank you for your input!

**Comment by FerranMarin** [comment]
Flexible number of accounts too!
Need to think about how to prepare all these files without going insane.

**Comment by CptCryptoVIP3P** [comment]
Flexible automatic % tiers based on average daily SLP since last claim. 
IE: 
25 SLP/Day = X%
40 SLP/Day = Y%
60 SLP/Day = Z%
etc...

**Comment by Rogalek** [comment]
I would love to have perfomance based payments like @CptCryptoVIP3P mentioned

**Comment by FerranMarin** [comment]
It's something I need to expand on. It will come in time.

**Comment by Rogalek** [comment]
One more option popup in my mind, penalties system, for example, your scholar have 1-2 days off in two weeks period, so it will be good that code will check how many days he skipped and for example each day above limit its penalty lets say 50 SLP.

If you show me how to get information like that I can try and propose some PR.

**Comment by FerranMarin** [comment]
Problem with this is... how do you propose that to be configured? Because if 1 manger wants to use it great, but I am sure not all want to use it this way so the flexibility means each manger can do whatever they do for their scholarship... I try to keep it generic as much as I can so it catters most cases. If you have a way to do such configurations, please, do make a proposal and we can work the details later on.
