### ISSUE TITLE
[BUG] Rare bug on Trezor

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#63]
**Describe the bug**
![imagen](https://user-images.githubusercontent.com/14543508/144155358-23a53dfe-ecb9-4bed-827b-70d4d14e1b49.png)

Might also need to add a small delay between payments, as sometimes it calculates wrong the nonce (specially in slower ronin days)

**To Reproduce**
It randomly happens in some transactions. Has to do with leading 0 bytes in parts of the signature and the rlp encode function.

**Additional context**
Problem apparently solved here: https://github.com/MOACChain/moac-core/issues/24
Been trying to fix it in branch trezor_rare_bug_fix

**Comment by mowens3** [comment]
Looks related to this issue. Occurs when many transfers are queued up from one address.
https://github.com/MOACChain/moac-core/issues/24

**Comment by mowens3** [comment]
It seems to only occur when many transfers are queued from one address. Maybe can do each individually in a loop.

**Comment by FerranMarin** [comment]
I think I've found the solution... releasing v.1.15 see if that does the trick....

**Comment by FerranMarin** [comment]
A week since release and this bug has not appeared again... I will close it for now, hope we do not need to re-open it
