### ISSUE TITLE
[BUG] 400 Client Error while transferring Axie from one wallet to another

### ISSUE THREAD

**Issue by iqbalhusen** [FerranMarin/axie-scholar-utilities#84]
Suddenly started getting this error from today. It worked perfectly before today.

File: `axie-scholar-utilities/axie-scholar-utilities/source/axie/transfers.py`
Line: 73 `self.w3.eth.send_raw_transaction(signed.rawTransaction)`
Error: `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://proxy.roninchain.com/free-gas-rpc`

**Comment by iqbalhusen** [comment]
> Do you have free tx's still available on the sender account? If not, that would be the cause.

I assume you mean "transaction" by tx. 

1. I am sorry if the question is very basic, but how can I check if the sender account has free tx or not? 
2. If not, then what would be the solution? Would I have to use the non-free RPC and provide some `gas` and `gasPrice` value?
3. If I have to use the non-free RPC, what value should I provide in `gas` and `gasPrice`. Would be so kind of you if you can share a code snippet.

**Comment by FerranMarin** [comment]
Yes tx is transaction, sorry!

1. Easiest way, check on the ronin wallet widget.
2. Both are options, problem is atm my code only works with free tx, I am implementing paid ones.
3. I will update library and this tools code once I develop and test it :)
