### ISSUE TITLE
[SUGGESTION] Any way to automate axie buying process?

### ISSUE THREAD

**Issue by iqbalhusen** [FerranMarin/axie-scholar-utilities#90]
Is it possible to automate axie buying process?

**Comment by FerranMarin** [comment]
Technically? Yes, but it is against their ToS, so you'd risk getting your axies banned.

**Comment by iqbalhusen** [comment]
> Technically? Yes, but it is against their ToS, so you'd risk getting your axies banned.

Any direction on how to do it for experimental purpose? Sorry if the question is unrelated to this library.
