### ISSUE TITLE
[BUG] poetry run python trezor_axie_scholar_cli.py config_trezor payments.json trezor_config.json Infinite loop?

### ISSUE THREAD

**Issue by Embidiel** [FerranMarin/axie-scholar-utilities#93]
**Describe the bug**
Tried running this command to generate trezor.json `poetry run python trezor_axie_scholar_cli.py config_trezor payments.json trezor_config.json`, it seems to run on an infinite loop. Entered my PIN and the seedphrase. Entered number of accounts, I have like 9 Ronin Accounts. Confirmed 9 times. I expected it to complete after confirming 9 times and then I entered my PIN again, seed phrase, number of accounts for about 15 times so in total I confirmed about 135 times on my Trezor. After entering trezor details 15 times, I exited the console. Am I missing something?

**To Reproduce**
1. Connect Trezor
2. Enter PIN
3. Enter seed phrase
4. Enter number of accounts
5. Confirm accounts on Trezor hardware.

**Expected behavior**
 I expected it to complete after confirming 9 times on my trezor hardware.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome

**Comment by FerranMarin** [comment]
So... you need to input TOTAL number of accounts in that seedphrase. They will try to match it to the scholar accounts in payments.json
So it will ask as many confirmations as number of accounts you input and it will keep asking for seedphrase/number of accounts, until all the accounst in payments.json have been matched.

**Comment by Embidiel** [comment]
Found the problem bro, I've written the AccountAddress property at "0x" format I checked the sample json, I found out that it's supposed to be in "ronin:" format. Thanks!
