### ISSUE TITLE
[QUESTION] Can we get statistics about account from your code?

### ISSUE THREAD

**Issue by Rogalek** [FerranMarin/axie-scholar-utilities#97]
Can we get everyday SLP, replays, and other stuff connected to the scholar account from your code?

Thank you.

**Comment by FerranMarin** [comment]
This is not something the code does, and I do not not see it taking this route. This code intent is mainly to carry out the tidious operations in an automated way.
Now, can that kind of thing be created? yes, but I'd recommend just using something like axie.management :)

**Comment by Rogalek** [comment]
Sometimes axie.management has lags or other issues, I would like to implement actually performance based payments for my scholars like here: https://github.com/FerranMarin/axie-scholar-utilities/issues/61#issuecomment-1073294389 another guy mention. I will follow that topic.
